name: Build Godot Project
on:
    push:
        branches: [main]
permissions:
    contents: read
    actions: read
    checks: write
    pull-requests: write
jobs:
    Godot:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                platform: [linux, windows, mac]
        steps:
            - uses: actions/checkout@v4
              with:
                  lfs: true
            - name: Create build directory
              run: |
                  mkdir builds
            - name: Build
              id: build
              uses: felix-schindler/build-godot-action@v2.0.0
              with:
                  name: Tortuga's Last Stand
                  preset: ${{ matrix.platform }}
                  debugMode: "false"
            - name: Upload Artifact
              uses: actions/upload-artifact@v4
              with:
                  name: Client - ${{ matrix.platform }}
                  path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
